# SLICE => IT IS AN INBULIT FUNCTION.
# IT APPLIES IF THE INDEXING IS APPLIED IN THE COLLECTION AND THE COLLECTION SHOULD BE ORDERD.

# SYNTAX => COLLECTION[START : STOP : STEP / DIRECTION / JUMP] 
#  DEFAULT SYNTAX => COLLECTION[START:STOP]

# RULES => 
# 1. FIND OUT STEPS DIRECTION, IF NOT GIVEN THEN IT IS BY DEFAULT POSITIVE DIRECTION(1).
# 2. FIND OUT STARTS STOP DIRECTION , IF NOT GIVEN THEN IT TAKES BY DEFAULT STEP DIRECTION.
# 3. IF BOTH DIRECTIONS ARE MATCH SO WE GET O/P BUT IF NOT , WE ALWAYS GET EMPTY O/P.


s='I LOVE PYTHON'

# EX 1.
# print(s[: :])


# EX 2.
# print(s[: : -1])


# EX 3. 
# print( s[2:5])


# EX 4. 
# print( s[2:5:-1])


# EX 5. 
#print( s[-1:-7])


# EX 6. 
#print(s[-9:-4])


# EX 7. 
# print(s[10:5])


# EX 8. 
# print( s[10:5:-1])


print(s[::-1][2:10][::-1][::-1])